In [ ]:
#Importing pandas library
import pandas as pd
#Loading data into a DataFrame
modified_data=pd.read_csv('/content/drive/MyDrive/SDGP Implementation/modified_data (1).csv')

In [ ]:
modified_data.shape

(4191, 6)

In [ ]:
x3 = modified_data[['Income']]
y3 = modified_data['Eating_Out']

In [ ]:
x3

            Income
0      6492.016466
1     38574.647021
2     11946.071980
3     11296.833460
4     10367.216239
...            ...
4186  12096.114950
4187   3701.811201
4188  17591.552094
4189  45208.132385
4190  14380.461643

[4191 rows x 1 columns]

In [ ]:
y3

0        309.239688
1       1267.553419
2        475.929401
3        553.772450
4        292.243613
           ...
4186     507.430462
4187      92.813579
4188     790.852849
4189    2067.915209
4190     591.611733
Name: Eating_Out, Length: 4191, dtype: float64

In [ ]:
from sklearn.model_selection import train_test_split
x3_train, x3_test, y3_train, y3_test = train_test_split(x3, y3, test_size=0.3, random_state=42)

In [ ]:
x3_train

            Income
1537  28070.688540
840   16107.744703
581   43265.114931
3226  11986.378772
2743  16190.071296
...            ...
3444  25485.014340
466   12526.378249
3092  43090.243632
3772  31087.289799
860   20454.246719

[2933 rows x 1 columns]

In [ ]:
len(x3_test)

1258

In [ ]:
from sklearn.linear_model import LinearRegression
clf3 = LinearRegression()
clf3.fit(x3_train, y3_train)

LinearRegression()

In [ ]:
clf3.predict(x3_test)

array([1060.53339248,  639.64121521,  886.37022673, ...,  314.55015741,
        179.50497074, 1289.03801914])

In [ ]:
y3_test

4085     757.047042
1732     733.531965
2242     593.236708
96      2387.000317
1657    1210.621447
           ...
2240     350.770925
195     1239.202730
874      263.470323
2618     101.447041
3536    1454.491099
Name: Eating_Out, Length: 1258, dtype: float64

In [ ]:
clf3.score(x3_test, y3_test)

0.8005985004912608

In [ ]:
clf3.coef_

array([0.03391709])

In [ ]:
clf3.intercept_

24.976047974317453

In [ ]:
clf3.predict([[10000]])

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([364.14695554])

In [ ]:
import joblib
joblib.dump(clf3, "my_model3.pkl")  # Saves the model

['my_model3.pkl']

In [ ]:
model3 = joblib.load("my_model3.pkl")

In [ ]:
clf3.predict([[10000]])

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([364.14695554])