In [ ]:
#Importing pandas library
import pandas as pd
#Loading data into a DataFrame
modified_data=pd.read_csv('/content/drive/MyDrive/SDGP Implementation/modified_data (1).csv')

In [ ]:
modified_data.shape

(4191, 6)

In [ ]:
x5 = modified_data[['Income']]
y5 = modified_data['Education']

In [ ]:
x5

            Income
0      6492.016466
1     38574.647021
2     11946.071980
3     11296.833460
4     10367.216239
...            ...
4186  12096.114950
4187   3701.811201
4188  17591.552094
4189  45208.132385
4190  14380.461643

[4191 rows x 1 columns]

In [ ]:
y5

0        590.048039
1       3475.976780
2        782.135316
3        804.278678
4          0.000000
           ...
4186     965.879070
4187     309.328708
4188    1599.953289
4189    3129.112069
4190       0.000000
Name: Education, Length: 4191, dtype: float64

In [ ]:
from sklearn.model_selection import train_test_split
x5_train, x5_test, y5_train, y5_test = train_test_split(x5, y5, test_size=0.3, random_state=42)

In [ ]:
x5_train

            Income
1537  28070.688540
840   16107.744703
581   43265.114931
3226  11986.378772
2743  16190.071296
...            ...
3444  25485.014340
466   12526.378249
3092  43090.243632
3772  31087.289799
860   20454.246719

[2933 rows x 1 columns]

In [ ]:
len(x5_test)

1258

In [ ]:
from sklearn.linear_model import LinearRegression
clf5 = LinearRegression()
clf5.fit(x5_train, y5_train)

LinearRegression()

In [ ]:
clf5.predict(x5_test)

array([1765.52192089, 1091.54766143, 1486.63460247, ...,  570.97964719,
        354.73191298, 2131.42617107])

In [ ]:
y5_test

4085    2290.890248
1732    1598.650923
2242       0.000000
96      4317.153562
1657    2456.068341
           ...
2240    1547.376201
195     2211.147000
874      761.834361
2618     389.395066
3536    2625.360377
Name: Education, Length: 1258, dtype: float64

In [ ]:
clf5.score(x5_test, y5_test)

0.42953451761838135

In [ ]:
clf5.coef_

array([0.05431141])

In [ ]:
clf5.intercept_

107.28488994980853

In [ ]:
clf5.predict([[10000]])

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([650.39895477])

In [ ]:
import joblib
joblib.dump(clf5, "my_model5.pkl")  # Saves the model

['my_model5.pkl']

In [ ]:
model5 = joblib.load("my_model5.pkl")

In [ ]:
clf5.predict([[10000]])

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([650.39895477])