In [ ]:
#Importing pandas library
import pandas as pd
#Loading data into a DataFrame
modified_data=pd.read_csv('/content/drive/MyDrive/SDGP Implementation/modified_data (1).csv')

In [ ]:
modified_data.shape

(4191, 6)

In [ ]:
x4 = modified_data[['Income']]
y4 = modified_data['Healthcare']

In [ ]:
x4

            Income
0      6492.016466
1     38574.647021
2     11946.071980
3     11296.833460
4     10367.216239
...            ...
4186  12096.114950
4187   3701.811201
4188  17591.552094
4189  45208.132385
4190  14380.461643

[4191 rows x 1 columns]

In [ ]:
y4

0        222.648418
1       1196.044202
2        404.436749
3        503.306245
4        468.318337
           ...
4186     476.766869
4187     116.764188
4188     782.073943
4189    2219.637354
4190     678.994977
Name: Healthcare, Length: 4191, dtype: float64

In [ ]:
from sklearn.model_selection import train_test_split
x4_train, x4_test, y4_train, y4_test = train_test_split(x4, y4, test_size=0.3, random_state=42)

In [ ]:
x4_train

            Income
1537  28070.688540
840   16107.744703
581   43265.114931
3226  11986.378772
2743  16190.071296
...            ...
3444  25485.014340
466   12526.378249
3092  43090.243632
3772  31087.289799
860   20454.246719

[2933 rows x 1 columns]

In [ ]:
len(x4_test)

1258

In [ ]:
from sklearn.linear_model import LinearRegression
clf4 = LinearRegression()
clf4.fit(x4_train, y4_train)

LinearRegression()

In [ ]:
clf4.predict(x4_test)

array([1209.59364057,  728.65821081, 1010.5848647 , ...,  357.19060928,
        202.88026948, 1470.69607192])

In [ ]:
y4_test

4085    1051.100099
1732     854.803230
2242    1124.995191
96      2010.187442
1657    1124.764846
           ...
2240     616.861877
195      962.903673
874      358.334311
2618     189.134408
3536    1127.872555
Name: Healthcare, Length: 1258, dtype: float64

In [ ]:
clf4.score(x4_test, y4_test)

0.9130704572593915

In [ ]:
clf4.coef_

array([0.0387556])

In [ ]:
clf4.intercept_

26.306700545770354

In [ ]:
clf4.predict([[10000]])

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([413.86274221])

In [ ]:
import joblib
joblib.dump(clf4, "my_model4.pkl")  # Saves the model

['my_model4.pkl']

In [ ]:
model4 = joblib.load("my_model4.pkl")

In [ ]:
clf4.predict([[10000]])

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([413.86274221])