In [ ]:
#Importing pandas library
import pandas as pd
#Loading data into a DataFrame
filtered_data=pd.read_csv('/content/drive/MyDrive/SDGP Implementation/filtered_data.csv')

In [ ]:
filtered_data.describe()

,Income,Age,Dependents,Rent,Loan_Repayment,Insurance,Groceries,Transport,Eating_Out,Entertainment,...,Desired_Savings,Disposable_Income,Potential_Savings_Groceries,Potential_Savings_Transport,Potential_Savings_Eating_Out,Potential_Savings_Entertainment,Potential_Savings_Utilities,Potential_Savings_Healthcare,Potential_Savings_Education,Potential_Savings_Miscellaneous
count,9.289000e+03,9289.000000,9289.000000,9289.000000,9289.000000,9289.000000,9289.000000,9289.000000,9289.000000,9289.000000,...,9289.000000,9289.000000,9289.000000,9289.000000,9289.000000,9289.000000,9289.000000,9289.000000,9289.000000,9289.000000
mean,4.168908e+04,28.444504,2.008289,9132.142173,2047.808469,1454.417542,5216.918285,2713.115588,1468.183746,1452.623652,...,5027.030166,10677.317017,917.359616,474.663561,255.428463,253.166824,439.978711,41.541450,63.078328,146.078547
std,4.126642e+04,6.385357,1.423939,9580.445160,4180.000884,1522.662849,5129.713716,2779.618381,1500.586442,1530.347375,...,8180.298080,12202.954070,1095.004315,548.654439,300.018087,301.442902,520.147169,55.710430,103.829971,177.112477
min,1.301187e+03,18.000000,0.000000,260.237467,0.000000,30.002012,154.078240,81.228584,39.437523,56.721325,...,0.000000,-5400.788673,16.575501,8.268076,3.797926,3.121610,7.033070,0.014734,0.000000,2.091973
25%,1.756521e+04,23.000000,1.000000,3629.174885,0.000000,574.757287,2136.776265,1118.752895,575.545616,574.212038,...,1218.092991,3762.300721,312.546500,161.654355,83.279743,83.556852,147.156736,10.989642,4.635517,47.589818
50%,3.008112e+04,28.000000,2.000000,6337.753670,0.000000,1005.496266,3725.332288,1923.445794,1025.519970,1019.931852,...,2148.471990,7196.843275,597.813617,301.858935,163.050988,165.464484,287.126943,25.050858,32.523046,92.458348
75%,5.137541e+04,34.000000,3.000000,11218.246053,2643.627666,1777.549428,6449.952323,3338.183304,1804.027986,1783.803694,...,6115.109924,13151.204187,1124.134124,589.540733,311.859822,310.539706,539.821782,52.025043,81.023451,180.088615
max,1.079728e+06,39.000000,4.000000,215945.674703,71235.964355,38734.932935,119816.898124,81861.503457,22962.605051,38667.368308,...,245504.485208,377060.218482,34894.644404,10950.745775,4734.251791,5626.666639,8081.799518,1394.531049,3647.244243,4637.951137

In [ ]:
filtered_data.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
Income,9289.0,41689.081028,41266.418376,1301.187333,17565.205298,30081.121640,51375.407362,1.079728e+06
Age,9289.0,28.444504,6.385357,18.000000,23.000000,28.000000,34.000000,3.900000e+01
Dependents,9289.0,2.008289,1.423939,0.000000,1.000000,2.000000,3.000000,4.000000e+00
Rent,9289.0,9132.142173,9580.445160,260.237467,3629.174885,6337.753670,11218.246053,2.159457e+05
Loan_Repayment,9289.0,2047.808469,4180.000884,0.000000,0.000000,0.000000,2643.627666,7.123596e+04
Insurance,9289.0,1454.417542,1522.662849,30.002012,574.757287,1005.496266,1777.549428,3.873493e+04
Groceries,9289.0,5216.918285,5129.713716,154.078240,2136.776265,3725.332288,6449.952323,1.198169e+05
Transport,9289.0,2713.115588,2779.618381,81.228584,1118.752895,1923.445794,3338.183304,8.186150e+04
Eating_Out,9289.0,1468.183746,1500.586442,39.437523,575.545616,1025.519970,1804.027986,2.296261e+04
Entertainment,9289.0,1452.623652,1530.347375,56.721325,574.212038,1019.931852,1783.803694,3.866737e+04
Utilities,9289.0,2510.894903,2582.403822,75.429414,1010.035684,1760.800877,3060.389685,5.115619e+04
Healthcare,9289.0,1671.687046,1678.591702,53.500761,680.736965,1187.217753,2052.436314,3.600153e+04
Education,9289.0,2510.584300,3213.089984,0.000000,579.950138,1696.067442,3313.651264,8.166509e+04
Miscellaneous,9289.0,833.388307,874.916982,20.503223,319.660679,577.118639,1021.055555,1.585636e+04
Desired_Savings_Percentage,9289.0,9.794111,3.919088,5.000180,6.953170,8.874662,11.815090,2.494008e+01
Desired_Savings,9289.0,5027.030166,8180.298080,0.000000,1218.092991,2148.471990,6115.109924,2.455045e+05
Disposable_Income,9289.0,10677.317017,12202.954070,-5400.788673,3762.300721,7196.843275,13151.204187,3.770602e+05
Potential_Savings_Groceries,9289.0,917.359616,1095.004315,16.575501,312.546500,597.813617,1124.134124,3.489464e+04
Potential_Savings_Transport,9289.0,474.663561,548.654439,8.268076,161.654355,301.858935,589.540733,1.095075e+04
Potential_Savings_Eating_Out,9289.0,255.428463,300.018087,3.797926,83.279743,163.050988,311.859822,4.734252e+03
Potential_Savings_Entertainment,9289.0,253.166824,301.442902,3.121610,83.556852,165.464484,310.539706,5.626667e+03
Potential_Savings_Utilities,9289.0,439.978711,520.147169,7.033070,147.156736,287.126943,539.821782,8.081800e+03
Potential_Savings_Healthcare,9289.0,41.541450,55.710430,0.014734,10.989642,25.050858,52.025043,1.394531e+03
Potential_Savings_Education,9289.0,63.078328,103.829971,0.000000,4.635517,32.523046,81.023451,3.647244e+03
Potential_Savings_Miscellaneous,9289.0,146.078547,177.112477,2.091973,47.589818,92.458348,180.088615,4.637951e+03

In [ ]:
filtered_data.shape

(9289, 27)

In [ ]:
filtered_data.head()

,Income,Age,Rent,Loan_Repayment,Insurance,Groceries,Transport,Eating_Out,Entertainment,Utilities,...,Desired_Savings,Disposable_Income,Potential_Savings_Groceries,Potential_Savings_Transport,Potential_Savings_Eating_Out,Potential_Savings_Entertainment,Potential_Savings_Utilities,Potential_Savings_Healthcare,Potential_Savings_Education,Potential_Savings_Miscellaneous
0,26858.596592,34,5371.719318,0.000000,869.522617,2818.444460,1543.018778,649.378103,1050.241738,1626.143346,...,1923.176434,9676.818733,540.306561,119.347139,141.866089,234.131168,286.668408,6.603212,56.306874,97.388606
1,50367.605084,35,7555.140763,4612.103386,2201.800050,6313.222081,3221.396403,1513.814376,1723.306926,3368.457108,...,7050.360422,13891.450624,1466.073984,473.549752,410.857129,459.965256,488.383423,7.290892,106.653597,138.542422
2,101455.600247,21,15218.340037,6809.441427,4889.418087,14690.149363,7106.130005,5040.249158,2858.194240,6128.550387,...,16694.965136,31617.953615,1875.932770,762.020789,1241.017448,320.190594,1389.815033,193.502754,0.000000,296.041183
3,20606.733121,32,6182.019936,3562.488826,1018.589940,3066.867220,1170.790666,688.059838,418.233816,921.232717,...,362.917872,362.917872,822.974023,212.998059,85.489142,97.812946,252.344383,9.984250,59.957848,80.754353
4,46304.790235,30,9260.958047,0.000000,2130.254825,5065.627032,2500.054847,2040.310666,1016.613164,2945.433561,...,5615.104745,15690.256276,962.019888,380.272262,598.882904,188.311642,793.644470,34.873044,39.738841,203.146675

In [ ]:
filtered_data = filtered_data.drop(columns=filtered_data.loc[:, 'Potential_Savings_Groceries':'Potential_Savings_Miscellaneous'].columns)
filtered_data=filtered_data.drop(['Dependents','Occupation','City_Tier','Miscellaneous','Loan_Repayment','Groceries','Desired_Savings_Percentage','Disposable_Income','Desired_Savings','Insurance','Entertainment','Utilities','Age'],axis=1)
filtered_data.describe(include="all").transpose()

,count,mean,std,min,25%,50%,75%,max
Income,5112.0,41913.573064,43262.760396,1301.187333,17261.639991,29872.735370,51272.858240,1.079728e+06
Rent,5112.0,9204.088674,9943.801312,260.237467,3630.873853,6292.240050,11145.873351,2.159457e+05
Transport,5112.0,2728.717380,2948.357784,81.228584,1100.187839,1903.612752,3320.296815,8.186150e+04
Eating_Out,5112.0,1469.207462,1523.910702,39.437523,565.846594,1025.793030,1793.581874,2.296261e+04
Healthcare,5112.0,1677.181533,1741.424410,53.500761,668.028388,1178.053294,2035.794094,3.600153e+04
Education,5112.0,2500.048033,3323.287012,0.000000,578.472099,1641.318384,3309.968110,8.166509e+04

In [ ]:
# Save the cleaned dataset
filtered_data.to_csv('prepared_data.csv', index=False)

# Download the new file
from google.colab import files
files.download('prepared_data.csv')

In [ ]:
#Importing pandas library
import pandas as pd
#Loading data into a DataFrame
prepared_data=pd.read_csv('/content/drive/MyDrive/SDGP Implementation/prepared_data.csv')

In [ ]:
prepared_data.head()

,Income,Rent,Transport,Eating_Out,Healthcare,Education
0,26858.596592,5371.719318,1543.018778,649.378103,1137.351325,1551.723167
1,50367.605084,7555.140763,3221.396403,1513.814376,2178.515847,3160.026299
2,101455.600247,15218.340037,7106.130005,5040.249158,4571.118217,0.000000
3,20606.733121,6182.019936,1170.790666,688.059838,830.237055,1939.226547
4,46304.790235,9260.958047,2500.054847,2040.310666,1649.757514,3085.991147

In [ ]:
prepared_data.shape

(5112, 6)

In [ ]:
prepared_data.describe()

,Income,Rent,Transport,Eating_Out,Healthcare,Education
count,5.112000e+03,5112.000000,5112.000000,5112.000000,5112.000000,5112.000000
mean,4.191357e+04,9204.088674,2728.717380,1469.207462,1677.181533,2500.048033
std,4.326276e+04,9943.801312,2948.357784,1523.910702,1741.424410,3323.287012
min,1.301187e+03,260.237467,81.228584,39.437523,53.500761,0.000000
25%,1.726164e+04,3630.873853,1100.187839,565.846594,668.028388,578.472099
50%,2.987274e+04,6292.240050,1903.612752,1025.793030,1178.053294,1641.318384
75%,5.127286e+04,11145.873351,3320.296815,1793.581874,2035.794094,3309.968110
max,1.079728e+06,215945.674703,81861.503457,22962.605051,36001.527365,81665.091857

In [ ]:
prepared_data.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
Income,5112.0,41913.573064,43262.760396,1301.187333,17261.639991,29872.735370,51272.858240,1.079728e+06
Rent,5112.0,9204.088674,9943.801312,260.237467,3630.873853,6292.240050,11145.873351,2.159457e+05
Transport,5112.0,2728.717380,2948.357784,81.228584,1100.187839,1903.612752,3320.296815,8.186150e+04
Eating_Out,5112.0,1469.207462,1523.910702,39.437523,565.846594,1025.793030,1793.581874,2.296261e+04
Healthcare,5112.0,1677.181533,1741.424410,53.500761,668.028388,1178.053294,2035.794094,3.600153e+04
Education,5112.0,2500.048033,3323.287012,0.000000,578.472099,1641.318384,3309.968110,8.166509e+04

In [ ]:
prepared_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5112 entries, 0 to 5111
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Income      5112 non-null   float64
 1   Rent        5112 non-null   float64
 2   Transport   5112 non-null   float64
 3   Eating_Out  5112 non-null   float64
 4   Healthcare  5112 non-null   float64
 5   Education   5112 non-null   float64
dtypes: float64(6)
memory usage: 239.8 KB